name: Demo Workflow
on:
  push:
    branches:
    - main
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - run: echo "Demo Actions" > demo.txt
    - uses: actions/upload-artifact@v4
      with:
        name: demo-artifact
        path: ./demo.txt
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: demo-artifact
    - run: cat demo.txt
